import "../styles/globals.css";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/navBar.module.css";
import React from "react";
import Modal from "../components/modal/modal";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>PlaceholderPageTitle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navBarContainer}>
        <div className={styles.navLeft}>
          <Link className={styles.linkHome} href="/">
            Monvieur parle
          </Link>
        </div>
        <div className={styles.navRight}>
          <Link className={styles.linkOther} href="/other">
            Sports
          </Link>
          <Link className={styles.linkOther} href="/other">
            Mode
          </Link>
          <Link className={styles.linkOther} href="/other">
            Technologique
          </Link>
          <Link className={styles.linkOther} href="/other">
            Cusine
          </Link>
          <Link className={styles.linkOther} href="/other">
            Culture
          </Link>
          <Link className={styles.linkOther} href="/other">
            Souri
          </Link>
          <Modal />
        </div>
      </div>

      <Component {...pageProps} />

      <div className={styles.footerContainer}>
        <Link className={styles.linkOther} href="/other">
          Contact
        </Link>
        <Link className={styles.linkOther} href="/other">
          Abonment
        </Link>
        <Link className={styles.linkOther} href="/other">
          Informations
        </Link>
        <Link className={styles.linkOther} href="/other">
          Éditeurs
        </Link>
        <Link className={styles.linkOther} href="/other">
          Culture
        </Link>
      </div>
    </>
  );
}
